# Generated by Django 6.0.1 on 2026-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_vehicle_type_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Tiền mặt'), ('TRANSFER', 'Chuyển khoản')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Chi phí sửa chữa (VNĐ)', max_digits=12, null=True),
        ),
    ]
