# Generated by Django 6.0.1 on 2026-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', help_text='Lý do hủy đơn'),
        ),
    ]
