# Generated by Django 6.0.1 on 2026-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='damage_image',
            field=models.ImageField(blank=True, help_text='Ảnh mức độ hư hỏng lúc gửi SOS', null=True, upload_to='sos_images/'),
        ),
    ]
