# Generated by Django 6.0.1 on 2026-03-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, default=None, help_text='Lý do hủy đơn', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
