# Generated by Django 6.0.1 on 2026-03-12 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_fix_chatmessage_text_and_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Nội dung khiếu nại chi tiết')),
                ('evidence_image', models.ImageField(blank=True, help_text='Ảnh bằng chứng (nếu có)', null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('INVESTIGATING', 'Đang điều tra'), ('RESOLVED', 'Đã giải quyết'), ('DISMISSED', 'Từ chối / Hủy')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Ghi chú nội bộ của Admin khi xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Đơn cứu hộ liên quan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, help_text='Thợ bị khiếu nại (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khiếu nại',
                'verbose_name_plural': 'Quản lý Khiếu nại',
                'ordering': ['-created_at'],
            },
        ),
    ]
