# Generated by Django 6.0.1 on 2026-03-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='mechanic',
        ),
        migrations.AddField(
            model_name='complaint',
            name='accused_user',
            field=models.ForeignKey(blank=True, help_text='Người bị khiếu nại (Khách hoặc Thợ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='Người tạo khiếu nại (Khách hoặc Thợ)', on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
