# Generated by Django 6.0.1 on 2026-03-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('services', '0003_review_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sos_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking'),
        ),
    ]
