# Generated by Django 6.0.1 on 2026-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_review_sos_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Tiền mặt'), ('TRANSFER', 'Chuyển khoản')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=10),
        ),
    ]
