# Generated by Django 6.0.1 on 2026-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', help_text='Lý do hủy'),
        ),
    ]
