# Generated by Django 6.0.1 on 2026-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Xe máy'), ('CAR', 'Ô tô'), ('ALL', 'Cả hai')], default='ALL', max_length=10),
        ),
    ]
