# Generated by Django 6.0.1 on 2026-03-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mechanicprofile_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Tên chủ tài khoản', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='bank_account_no',
            field=models.CharField(blank=True, help_text='Số tài khoản', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Tên viết tắt Ngân hàng (VD: MB, VCB)', max_length=50, null=True),
        ),
    ]
