# Generated by Django 6.0.1 on 2026-03-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicPerformance',
            fields=[
            ],
            options={
                'verbose_name': 'Hiệu suất Thợ',
                'verbose_name_plural': 'Bảng Xếp Hạng Hiệu Suất',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.mechanicprofile',),
        ),
    ]
