# Generated by Django 6.0.1 on 2026-02-28 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('severity', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True)),
                ('estimated_price', models.CharField(blank=True, max_length=100)),
                ('recommended_action', models.TextField(blank=True)),
                ('can_drive', models.BooleanField(default=True)),
                ('urgency_level', models.IntegerField(default=1)),
                ('ai_powered', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
