# Generated by Django 6.0.1 on 2026-03-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='labor_cost',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='aireport',
            name='parts_cost',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='aireport',
            name='price_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='estimated_price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
