# Generated by Django 6.0.1 on 2026-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aireport_labor_cost_aireport_parts_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='source',
            field=models.CharField(choices=[('image', 'Ảnh'), ('sound', 'Âm thanh')], default='image', max_length=10),
        ),
    ]
